
SOLVENTS = {
 'C1CCCCC1': 'cyclohexane',
 'C1CCOC1': 'THF',
 'C1COCCO1': '1,4-dioxane',
 'CC#N': 'MeCN;acetonitrile',
 'CC(=O)N(C)C': 'DMA;dimethylacetamide',
 'CC(C)(C)O': 't-BuOH;tert-butanol',
 'CC(C)=O': 'acetone',
 'CC(C)CO': 'i-BuOH;isobutanol',
 'CC(C)O': 'isopropanol',
 'CC(Cl)Cl': '1,1-dichloroethane;ethylidene chloride',
 'CC1CCCO1': '2-MeTHF;2-methyl-THF',
 'CCC(C)=O': 'MEK;butanone',
 'CCCCC': 'pentane',
 'CCCCCC': 'hexane',
 'CCCCCCC': 'heptane',
 'CCCCO': 'n-BuOH;n-butanol',
 'CCCO': '1-propanol',
 'CCO': 'EtOH;ethanol',
 'CCOC(C)=O': 'EtOAc;ethyl acetate',
 'CCOCC': 'Et2O;diethyl ether',
 'CN(C)C=O': 'DMF',
 'CN(C)P(=O)(N(C)C)N(C)C': 'HMPA',
 'CN1CCCC1=O': 'N-methyl-2-pyrrolidone;NMP',
 'CO': 'MeOH;methanol',
 'COC(C)(C)C': 'MTBE;Methyl tert-butyl ether;methyl tert-butyl ether',
 'COCCOC': '1,2-DME;DME',
 'CS(C)=O': 'DMSO',
 'Cc1ccc(C)cc1': 'p-xylene',
 'Cc1cccc(C)c1': 'm-xylene',
 'Cc1ccccc1': 'toluene',
 'Cc1ccccc1C': 'o-xylene',
 'ClC(Cl)(Cl)Cl': 'CCl4;carbon tetrachloride',
 'ClC(Cl)Cl': 'chloroform',
 'ClCCCl': '1,2-dichloroethane',
 'ClCCl': 'DCM;dichloromethane',
 'Clc1ccccc1': 'chlorobenzene',
 'Clc1ccccc1Cl': '1,2-dichlorobenzene',
 'O': 'water',
 'OCCO': 'ethylene glycol',
 'S=C=S': 'CS2;carbon disulfide',
 'c1ccccc1': 'benzene',
 'C1CCCC1': 'cyclopentane',
 'CNC(C)=O': 'N-methylacetamide',
 'CC(=O)O': 'acetic acid',
 'C[N+](=O)[O-]': 'nitromethane',
 'O=C(O)C(F)(F)F': 'TFA',
 'c1ccncc1': 'pyridine',
 'C1COCCOCCOCCOCCO1': 'EYO',
 'CC(=O)C#N': 'AcCN',
 'CC=C(C)C': 'pentene',
 'CCCC#N': 'butyronitrile',
 'CCCC(C)O': '2-pentanol',
 'CCCCCCCCCCCC': 'dodecane',
 'COC': 'dimethyl ether',
 'COC(C)=O': 'methyl acetate',
 'COC1CCCC1': 'CPME',
 'CS(C)(=O)=O': 'DMSO2',
 'CSC': 'DMS',
 'Cc1ccc(C(C)C)cc1': 'p-cymene',
 'N#Cc1ccccc1': 'benzonitrile',
 'OC(C(F)(F)F)C(F)(F)F': 'HFIP',
 'OCC(F)(F)F': 'TFE',
 'OCc1ccccc1': 'benzyl alcohol',
 '[2H]C(Cl)(Cl)Cl': 'CDCl3',
 'c1ccsc1': 'thiophene',
 'CC(=O)CC(C)C': '4-methylpentan-2-one;MIBK',
 'CC(=O)OC(C)C': 'isopropyl acetate',
 'CC(C)CCO': '3-methyl-1-butanol;isoamyl alcohol',
 'CC(C)OC(C)C': 'DIPE;diisopropyl ether',
 'CCC#N': 'propionitrile',
 'CCC(C)(C)O': 'tert-amyl alcohol',
 'CCC(C)O': '2-butanol;s-BuOH',
 'CCCC(C)C': 'isohexane',
 'CCCCCO': '1-pentanol;pentanol',
 'CCCCOC(C)=O': 'butyl acetate',
 'CCCCOCCCC': 'butyl ether;dibutyl ether',
 'CCOCCO': '2-ethoxyethanol',
 'CCc1ccccc1': 'ethylbenzene',
 'CN1CCN(C)C1=O': '1,3-dimethyl-2-imidazolidinone;DMI',
 'COCC(C)O': '1-methoxy-2-propanol;methoxyisopropanol',
 'COCCO': '2-methoxyethanol;methoxyethanol',
 'COCCOCCOC': 'diglyme',
 'COc1ccccc1': 'anisole',
 'Cc1cc(C)cc(C)c1': 'mesitylene',
 'O=S1(=O)CCCC1': 'sulfolane',
 'OCC(O)CO': 'glycerin;glycerol',
 'OCC1CCCO1': 'THFA',
 'OCCOCCO': 'diethylene glycol',
 'c1ccc(Oc2ccccc2)cc1': 'diphenyl ether',
 'CC(=O)OC(C)(C)C': 'tert-butyl acetate',
 'CC=O': 'acetaldehyde',
 'CN1CCCN(C)C1=O': 'DMPU',
 'COC(C)O': '1-methoxyethanol',
 'FC(F)(F)c1ccccc1': 'trifluorotoluene',
 'O=[N+]([O-])c1ccccc1': 'nitrobenzene',
 'Oc1ccccc1': 'phenol'
 }